name: Build NPM package

on: [push]

jobs:
  build-all:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: .

      - name: Generate nodes from widgets
        run: ./scripts/generate-nodes.sh

      - name: Remove widgets
        run: rm -r widgets
      
      - name: npm bump version
        run: npm version patch
  
      - name: npm publish
        uses: JS-DevTools/npm-publish@v1
        id: publish
        with:
          access: "public"
          token: ${{ secrets.NPM_AUTH_TOKEN }} # from repo settings

      - name: Create annotation
        run: |
          echo "::notice title=NPM module::Version ${{steps.publish.outputs.version}}"
